name: Rust Build and Release

on:
  push:
    branches: [ main, master ]
    tags:
      - 'v*' # Run workflow on version tags, e.g. v1.0.0

env:
  CARGO_TERM_COLOR: always
  RELEASE_BIN: openrouter-proxy

jobs:
  build:
    name: Build and Release
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            artifact_name: your-app-name
            asset_name: your-app-name-linux-amd64
    
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
    
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --release --all-features
    
    - name: Run tests
      uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.asset_name }}
        path: target/release/${{ matrix.artifact_name }}
        retention-days: 5
    
    # Create GitHub release when a version tag is pushed
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/v') && matrix.os == 'ubuntu-latest'
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
    
    # Upload release assets when a version tag is pushed
    - name: Upload Release Asset
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: ./target/release/${{ matrix.artifact_name }}
